services:
  - type: web
    name: whatsapp-condo-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn src.run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0